Libreria
matytaa/aydoo-2018 pull request #3
Opened 2018-04-24 03:40 UTC by matytaa

Creando pull request previo a entrega

2018-04-29 11:24 UTC, anero requested changes

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/ArticuloLibreria.java
> +    private final Double denominador = 100.0;
la convención para las constantes es ponerle el nombre todo en mayúsculas

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +        return this.listaDeSuscripciones;
al devolver una referencia a la colección de suscripciones estás rompiendo el encapsulamiento: se puede modificar externamente sin utilizar el método `comprarSuscripcion`. Para evitarlo tendrías que devolver una interfaz que permita iterar sobre la colección sin modificarla, o devolver una copia de la colección que si se modifica externamente no afecta el estado del objeto `Cliente`

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +        return this.misProductos;
mismo comentario sobre la ruptura del encapsulamiento

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +                            unaCompra.darListaDeProducto().iterator();
para evitar tanto acoplamiento entre el objeto `Libreria` y `Compra` / `Producto` deberías mover la responsabilidad de calculcar el valor total de la compra al objeto `Compra`

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +        return unProducto instanceof Periodico;
no es correcto preguntar la clase de un objeto, tenés que resolverlo con polimorfismo en vez de hacer esto.

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +            }
de nuevo: le clase `Libreria` tiene demasiado conocimiento sobre como funcionan los demás objetos, lo que hace que este demasiado acoplado a ellos. Revisa donde debería ir cada responsabilidad.

2018-04-29 11:24 UTC, anero commented on libreria/src/test/java/ar/edu/untref/aydoo/ClienteTest.java
> +    public void crearUnCliente() {
el nombre del test tiene que explicar que se esta probando, ejemplo para este caso: `nombreYDireccionSeAsignanCorrectamente`

2018-04-29 11:24 UTC, anero commented on libreria/src/test/java/ar/edu/untref/aydoo/LibreriaTest.java
> +        compra4.agregarUnProducto(boxes);
a los tests se les debería aplicar las mismas reglas que aplican al código productivo: si tenés código duplicado deberías refactorizarlo a un método.

2018-04-29 11:24 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +                                   final Producto unPeriodico) {
no cumple la consigna: el descuento de 5% para clientes registrados no se aplica en ningún lado

2018-05-07 03:33 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +                            unaCompra.darListaDeProducto().iterator();
Se movió la responsabilidad al objeto compra según el comentario

2018-05-07 03:34 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Compra.java
> +        return this.misProductos;
Corregido

2018-05-07 03:35 UTC, matytaa commented on libreria/src/test/java/ar/edu/untref/aydoo/LibreriaTest.java
> +        compra4.agregarUnProducto(boxes);
se agregó un @before en LibreriaTest

2018-05-07 03:52 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/ArticuloLibreria.java
> +    private final Double denominador = 100.0;
Corregido

2018-05-07 03:54 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Cliente.java
> +        return this.listaDeSuscripciones;
según la puesta en común realizada en clases realicé el cambio de que una suscripción es un producto, por lo cual el cliente no tendrá las suscripciones

2018-05-07 03:55 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +        return unProducto instanceof Periodico;
corregido

2018-05-07 03:55 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +            }
corregido

2018-05-07 03:55 UTC, matytaa commented on libreria/src/test/java/ar/edu/untref/aydoo/ClienteTest.java
> +    public void crearUnCliente() {
corregido

2018-05-07 03:56 UTC, matytaa commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +                                   final Producto unPeriodico) {
implementado

2018-05-08 03:06 UTC, anero approved these changes

2018-05-08 03:06 UTC, anero commented on libreria/src/main/java/ar/edu/untref/aydoo/Libreria.java
> +        }
El descuento por cliente registrado no debería aplicarse a compras que ya tengan el descuento por suscripción anual

2018-05-12 17:17 UTC, merged