Fibo3
matytaa/aydoo-2018 pull request #4
Opened 2018-05-01 18:53 UTC by matytaa

Claramente se debe optimizar el método recibirParametros(), pero no se como.

2018-05-07 02:00 UTC, anero requested changes

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/Fibonacci.java
> +    public int calcularFibonacci(int unNumeroFibonacci) {
Si la clase ya se llama `Fibonacci` es un poco repetitivo nombrar el método `calcularFibonacci` (con `calcular` alcanzaria)

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/Fibonacci.java
> +    }
Código obsoleto

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +        this.eureka = false;
??? las variables tienen que tener nombres claros. Por otro lado, ¿por qué es un atributo y no una variable local? 
Los atributos representan el estado de un objeto, ¿qué querría decir que `ProcesadorDeParametros` tenga `eureka` con valor `true`?

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ManejadorFibonacci.java
> +    }
El método `main` no corresponde a este objeto, estás mezclando responsabilidades...

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +                || (parametros.equals(""))) {
Verificar el string completo del parámetro no es una solución que escale. Si a `-o` decidimos agregarle un par de valores más (ej: valores `x` e `y` -> `-o=vdx`) vas a tener que agregar 4 condiciones adicionales al if

2018-05-07 02:00 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +    }
Tener setters para estos atributos rompe el encapsulamiento: deberían calcularse desde los parámetros del programa y el objeto solo debería permitir consultar sus valores

2018-05-07 02:00 UTC, anero commented on fibo3/src/test/java/ar/edu/untref/aydoo/GenerardorDeArchivosTest.java
> +        miGenerador.escribirArchivo("hola soy goku");
Cual es el test acá? No estás verificando nada del resultado de ejecutar el método

2018-05-07 04:05 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/ManejadorFibonacci.java
> +    }
Por? En cuál objeto iría? Para entender el por qué no

2018-05-07 04:13 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/Fibonacci.java
> +    }
eliminado

2018-05-07 04:14 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/Fibonacci.java
> +    public int calcularFibonacci(int unNumeroFibonacci) {
corregido

2018-05-07 04:19 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +    }
No entendí, los métodos imprimeEnVertical(), ejecutarEnOrdenInverso(), aplicarSumaDeValores() me quedaron como public por haberlos implementados en un TDD. Pero, al realizar el refactor me olvidé de modificarlos a private. No se si te referías a eso

2018-05-07 04:21 UTC, matytaa commented on fibo3/src/test/java/ar/edu/untref/aydoo/GenerardorDeArchivosTest.java
> +        miGenerador.escribirArchivo("hola soy goku");
Estaba probando generar un archivo con un nombre y un cuerpo dado. Está mal el test o el "hola soy goku"?

2018-05-07 04:23 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +        this.eureka = false;
eureka es una expresión que denota hallazgo o consecución que se busca con afán, pero si no es un nombre feliz lo cambiaré. Para mí era el nombre que cuadraba a la perfección

2018-05-07 11:51 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ManejadorFibonacci.java
> +    }
El objeto tiene demasiadas responsabilidades distintas: es el punto de entrada del programa (`main`), se encarga de inicializar los objetos que calculan la serie y que parsean los parámetros, y se encarga de generar la salida del programa. Me parece bien que funcione como un controlador, inicializando los demás objetos e invocando los métodos correspondientes pero entonces tanto el `main` como los métodos asociados a imprimir los resultados en pantalla o guardarlos en un archivo deberían estar en otros objetos. Para el `main` podés usar el mismo enfoque que en el proyecto base: tener una clase `Program` que lo único que hace es declarar el `main` e inicializar el `ManejadorFibonacci` pasandole los parámetros.

2018-05-07 11:56 UTC, anero commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +        this.eureka = false;
Cuadra perfecto si sos Arquímedes :)
Si la variable es `true` cuando se logra mapear un parámetro a un comportamiento tal vez un nombre más feliz sería `parámetroInterpretado` o algo así...
Más allá del nombre revisa el hecho de que sea un atributo, no me parece que este representando un estado del objeto sino más bien que lo estas usando para comunicación entre métodos lo que no es correcto (para eso existen los parámetros y los valores de retorno).

2018-05-07 23:57 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +        this.eureka = false;
ajustado

2018-05-08 03:24 UTC, matytaa commented on fibo3/src/main/java/ar/edu/untref/aydoo/ProcesadorDeParametros.java
> +                || (parametros.equals(""))) {
Corregido, se mudó a expresión regular

2018-05-11 02:31 UTC, anero approved these changes

2018-05-12 17:21 UTC, merged